#!/bin/bash

cd "$(dirname $0)"

if [ ! -d ~/.emacs.d ]; then
	mkdir ~/.emacs.d
fi

stow -d ./home -t ~ .

# TODO:
#   Implement a custom replacement for stow that better fits the use case.
#     - Don't symlink directories unless explicitly configured to do so.
