#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

# NIX_PATH and channels are gross, we ingnore them and build up channels of our own
# we only need to do this becasue home-manager assumes certain channels are present
unset NIX_PATH
NIX_PATH="$(nix-instantiate --eval --strict --json -E '(import ./nix/nix {}).bddap.shitty-nixpath' | jq -r)"
export NIX_PATH

home-manager -v build -f ./nix/home-manager/home.nix --no-out-link

if [ -n "${1+x}" ]; then
    home-manager build -f ./nix/home-manager/home.nix --no-out-link "$1"
fi
