#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

# NIX_PATH and channels are gross, we ignore them and build up channels of our own
# we only need to do this because home-manager assumes certain channels are present
unset NIX_PATH
NIX_PATH="$(cat "$(nix-build --no-out-link -E '(import ./nix/nix {}).bddap.shitty-nixpath')")"
export NIX_PATH

home-manager -v build -f ./nix/home-manager/home.nix --no-out-link "$@"
