# Host profile for testhost. Generated by ./install-to-disk.
# Machine-specific tuning (e.g. a nixos-hardware profile) goes here.
{ ... }: {
  imports = [
    ../common.nix
    ../laptop-hardware.nix
  ];

  networking.hostName = "testhost";
}
